version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
      target: prod
    image: happy_eat_fast_api:${HAPPY_EAT_FAST_API_VERSION:-latest}
    restart: always
    env_file:
    - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      rmq:
        condition: service_healthy
      kafka:
        condition: service_healthy
    environment:
      HAPPY_EAT_FAST_API_HOST: 0.0.0.0
      HAPPY_EAT_FAST_API_DB_HOST: happy_eat_fast_api-db
      HAPPY_EAT_FAST_API_DB_PORT: 5432
      HAPPY_EAT_FAST_API_DB_USER: happy_eat_fast_api
      HAPPY_EAT_FAST_API_DB_PASS: happy_eat_fast_api
      HAPPY_EAT_FAST_API_DB_BASE: happy_eat_fast_api
      HAPPY_EAT_FAST_API_RABBIT_HOST: happy_eat_fast_api-rmq
      HAPPY_EAT_FAST_API_REDIS_HOST: happy_eat_fast_api-redis
      TESTKAFKA_KAFKA_BOOTSTRAP_SERVERS: '["happy_eat_fast_api-kafka:9092"]'

  db:
    image: postgres:13.8-bullseye
    hostname: happy_eat_fast_api-db
    environment:
      POSTGRES_PASSWORD: "happy_eat_fast_api"
      POSTGRES_USER: "happy_eat_fast_api"
      POSTGRES_DB: "happy_eat_fast_api"
    volumes:
    - happy_eat_fast_api-db-data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: pg_isready -U happy_eat_fast_api
      interval: 2s
      timeout: 3s
      retries: 40

  migrator:
    image: happy_eat_fast_api:${HAPPY_EAT_FAST_API_VERSION:-latest}
    restart: "no"
    command: alembic upgrade head
    environment:
      HAPPY_EAT_FAST_API_DB_HOST: happy_eat_fast_api-db
      HAPPY_EAT_FAST_API_DB_PORT: 5432
      HAPPY_EAT_FAST_API_DB_USER: happy_eat_fast_api
      HAPPY_EAT_FAST_API_DB_PASS: happy_eat_fast_api
      HAPPY_EAT_FAST_API_DB_BASE: happy_eat_fast_api
    depends_on:
      db:
        condition: service_healthy

  redis:
    image: bitnami/redis:6.2.5
    hostname: "happy_eat_fast_api-redis"
    restart: always
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    healthcheck:
      test: redis-cli ping
      interval: 1s
      timeout: 3s
      retries: 50

  rmq:
    image: rabbitmq:3.9.16-alpine
    hostname: "happy_eat_fast_api-rmq"
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    healthcheck:
      test: rabbitmq-diagnostics check_running -q
      interval: 3s
      timeout: 3s
      retries: 50

  zookeeper:
    image: "bitnami/zookeeper:3.7.1"
    hostname: "happy_eat_fast_api-zookeeper"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
      ZOO_LOG_LEVEL: "ERROR"
    healthcheck:
      test: zkServer.sh status
      interval: 1s
      timeout: 3s
      retries: 30

  kafka:
    image: "bitnami/kafka:3.2.0"
    hostname: "happy_eat_fast_api-kafka"
    environment:
      KAFKA_BROKER_ID: "1"
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_LISTENERS: "PLAINTEXT://0.0.0.0:9092"
      KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://happy_eat_fast_api-kafka:9092"
      KAFKA_CFG_ZOOKEEPER_CONNECT: "happy_eat_fast_api-zookeeper:2181"
    healthcheck:
      test: kafka-topics.sh --list --bootstrap-server localhost:9092
      interval: 1s
      timeout: 3s
      retries: 30
    depends_on:
      zookeeper:
        condition: service_healthy



volumes:
  happy_eat_fast_api-db-data:
    name: happy_eat_fast_api-db-data
